# Generated by Django 4.2.9 on 2026-02-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='api_lesson_module__67aa6d_idx'),
        ),
    ]
